baseURL = "http://www.mischaf.com"
title = "Mischa Friegang"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
pygmentsStyle = "api"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
enableEmoji = true
# Enable Disqus comments
# disqusShortname = "yourdiscussshortname"

[params]
author = "Mischa Friegang"
description = "Mischa's Personal Website"
keywords = "blog"
info = ["Adventurer", "Nerd"]
avatarURL = "images/mischa.jpg"
#gravatar = "mischatravis10@gmail.com"
hideFooter = false
hideCredits = false
hideCopyright = false
since = 2019


colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Enable Twemoji
enableTwemoji = false
# Custom CSS
customCSS = []
# Custom SCSS
customSCSS = []
# Custom JS
customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'", "https://fonts.gstatic.com", "https://cdn.jsdelivr.net/"]
formaction = ["'self'"]
framesrc = ["'self'"]
imgsrc = ["'self'", "https://m1sc.net", "https://s3.us-west-1.wasabisys.com/"]
objectsrc = ["'none'"]
stylesrc = [
  "'self'",
  "'unsafe-inline'",
  "https://fonts.googleapis.com/",
  "https://cdn.jsdelivr.net/"
]
scriptsrc = ["'self'", "'unsafe-inline'", "https://www.google-analytics.com"]
prefetchsrc = ["'self'"]
# connect-src directive – defines valid targets for to XMLHttpRequest (AJAX), WebSockets or EventSource
connectsrc = ["'self'", "https://www.google-analytics.com",]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github"
weight = 1
url = "https://github.com/jinja2ninja/"



#[[params.social]]
#name = "LinkedIn"
#icon = "fa fa-linkedin"
#weight = 4
#url = "https://www.linkedin.com/in/mischa-friegang-943274215/"


[languages.en]
languageName = ":us:"

[[languages.en.menu.main]]
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Blog"
weight = 2
url = "posts/"

[markup.goldmark.renderer]
unsafe= true
